demo of a working pg database
Equal-Vote/star-server pull request #16
Opened 2021-12-26 17:16 UTC by scottPlusPlus

2021-12-27 05:12 UTC, ArendPeter requested changes
Aside from the conflicts, it looks good to me!

2021-12-29 02:46 UTC, scottPlusPlus commented on backend/src/index.ts
> +<<<<<<< HEAD
whoops.  okay, I think I fixed it.

2021-12-29 03:13 UTC, mikefranze commented on backend/src/index.ts
> +<<<<<<< HEAD
Looks good to me

2021-12-29 04:10 UTC, ArendPeter approved these changes
Looks great!

2021-12-29 04:11 UTC, merged

2021-12-29 04:41 UTC, mikefranze commented
Looks like it errored in the build process in heroku 
> tsc --project ./

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'pg'
Require stack:
- /app/backend/build/backend/src/test/DBTest.js
- /app/backend/build/backend/src/test/TempTestSuite.js
- /app/backend/build/backend/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/app/backend/build/backend/src/test/DBTest.js:15:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/backend/build/backend/src/test/DBTest.js',
    '/app/backend/build/backend/src/test/TempTestSuite.js',
    '/app/backend/build/backend/src/index.js'
  ]
}

2021-12-29 20:05 UTC, mikefranze commented
pg needed to be added to dependencies list. How do you run this test to see that it works?

2021-12-29 21:13 UTC, mikefranze commented
Never mind, figured it out and it works!