feat: publlic elections tab implemented
Equal-Vote/star-server pull request #549
Opened 2024-04-13 17:17 UTC by Jeetch8

Resolving issue #545

2024-04-13 20:04 UTC, ArendPeter requested changes
Thanks for making this change!

I left some minor comments, but overall it looks great

2024-04-13 20:04 UTC, ArendPeter commented on packages/backend/src/Models/Elections.ts
> +            .where("is_public", "=", true)
Can you remove this one?

getElections will also needs to be able to query private elections

2024-04-14 05:53 UTC, Jeetch8 commented
Hi Sir, 
thank u for your feedback. I've made the changes. Please take a look.

2024-04-14 06:23 UTC, ArendPeter approved these changes
Looks good, thanks for making the changes!

2024-04-14 06:24 UTC, merged

2024-04-14 06:25 UTC, ArendPeter commented
Great work, I merged your PR

Here's the corresponding frontend issue, in case you're interested in taking up another task: https://github.com/Equal-Vote/star-server/issues/471